[core]
# Gebruik de kiosk-shell in plaats van desktop-shell
shell=kiosk-shell.so
# Voorkom dat Weston na inactiviteit het scherm uitschakelt
idle-time=0

[shell]
# Zorg dat de cursor eventueel verborgen wordt als het een puur display-scherm is
cursor-theme=default

[autostart]
# Start de Rust binary direct full-screen op onder Wayland
path=/usr/bin/env WINIT_UNIX_BACKEND=wayland /usr/bin/lipl-display-femtovg
