[core]
# use the kiosk-shell instead of the desktop-shell
shell=kiosk-shell.so
# Prevent Weston to turn off the screen when idle
idle-time=0

[shell]
# Make sure the cursor is hidden when not using mouse or keyboard
cursor-theme=default

[autolaunch]
# Start de Rust binary direct full-screen op onder Wayland
path=/usr/bin/lipl-display-femtovg
